# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: SmeltCMS

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2


# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can add packaging information here
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  smeltHome:
    handler: handler.smelt
    events:
      - http:
          path: smelt
          method: get
  smeltList:
    handler: handler.smelt
    events:
      - http:
          path: smelt/list
          method: get
  smeltNew:
    handler: handler.smelt
    events:
      - http:
          path: smelt/new
          method: get

  smeltGenerate:
    handler: generate.handler
    events:
      - http:
          path: smelt/generate
          method: get

resources:  
  Resources:
    PublicS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: smelt-dev-public
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Items
        AttributeDefinitions:
          - AttributeName: ItemId
            AttributeType: S
        KeySchema:
          - AttributeName: ItemId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    SmeltIAMPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: smelt-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Scan
              Resource: arn:aws:dynamodb:*:*:table/Items
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: arn:aws:s3:::smelt-dev-public
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: arn:aws:s3:::smelt-dev-public/*

        Roles:
          - Ref: IamRoleLambdaExecution


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
